/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as LotCalculatorRouteImport } from './routes/lot-calculator'
import { Route as RiskCalculatorRouteImport } from './routes/risk-calculator'
import { Route as TradesRouteImport } from './routes/trades'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const LotCalculatorRoute = LotCalculatorRouteImport.update({
  id: '/lot-calculator',
  path: '/lot-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskCalculatorRoute = RiskCalculatorRouteImport.update({
  id: '/risk-calculator',
  path: '/risk-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/lot-calculator': typeof LotCalculatorRoute
  '/risk-calculator': typeof RiskCalculatorRoute
  '/trades': typeof TradesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/lot-calculator': typeof LotCalculatorRoute
  '/risk-calculator': typeof RiskCalculatorRoute
  '/trades': typeof TradesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/lot-calculator': typeof LotCalculatorRoute
  '/risk-calculator': typeof RiskCalculatorRoute
  '/trades': typeof TradesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/calendar'
    | '/lot-calculator'
    | '/risk-calculator'
    | '/trades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/calendar'
    | '/lot-calculator'
    | '/risk-calculator'
    | '/trades'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auth'
    | '/calendar'
    | '/lot-calculator'
    | '/risk-calculator'
    | '/trades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  LotCalculatorRoute: typeof LotCalculatorRoute
  RiskCalculatorRoute: typeof RiskCalculatorRoute
  TradesRoute: typeof TradesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lot-calculator': {
      id: '/lot-calculator'
      path: '/lot-calculator'
      fullPath: '/lot-calculator'
      preLoaderRoute: typeof LotCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-calculator': {
      id: '/risk-calculator'
      path: '/risk-calculator'
      fullPath: '/risk-calculator'
      preLoaderRoute: typeof RiskCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  LotCalculatorRoute: LotCalculatorRoute,
  RiskCalculatorRoute: RiskCalculatorRoute,
  TradesRoute: TradesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
